### ISSUE TITLE
GUI, NotImplementedError

### ISSUE THREAD

**Issue by CHDTevior** [limuloo/MIGC#14]
When I was using the GUI, I encountered the following error:

127.0.0.1 - - [22/Oct/2024 03:24:39] "POST /get_image HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/autodl-tmp/MIGC/migc_gui/app.py", line 113, in get_image
    fig_name = future.result()  # Block and wait until image processing is completed
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/autodl-tmp/MIGC/migc_gui/app.py", line 84, in process_request
    pipe = pipe.to("cuda")
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py", line 431, in to
    module.to(device, dtype)
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2958, in to
    return super().to(*args, **kwargs)
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1340, in to
    return self._apply(convert)
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 927, in _apply
    param_applied = fn(param)
  File "/root/miniconda3/envs/MIGC_diffusers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1333, in convert
    raise NotImplementedError(
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.

**Comment by CHDTevior** [comment]
This is my conda env:
(MIGC_diffusers) root@autodl-container-050e4299dc-db9f03e7:~/autodl-tmp/MIGC/migc_gui# pip list
Package                  Version    Editable project location
------------------------ ---------- -------------------------
accelerate               1.0.1
antlr4-python3-runtime   4.9.3
blinker                  1.8.2
certifi                  2024.8.30
charset-normalizer       3.4.0
click                    8.1.7
diffusers                0.30.3
einops                   0.8.0
filelock                 3.16.1
Flask                    3.0.3
Flask-Cors               5.0.0
fsspec                   2024.9.0
huggingface-hub          0.26.0
idna                     3.10
importlib_metadata       8.5.0
itsdangerous             2.2.0
Jinja2                   3.1.4
MarkupSafe               3.0.2
MIGC                     0.1        /root/autodl-tmp/MIGC
mpmath                   1.3.0
networkx                 3.2.1
numpy                    2.0.2
nvidia-cublas-cu12       12.4.5.8
nvidia-cuda-cupti-cu12   12.4.127
nvidia-cuda-nvrtc-cu12   12.4.127
nvidia-cuda-runtime-cu12 12.4.127
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.2.1.3
nvidia-curand-cu12       10.3.5.147
nvidia-cusolver-cu12     11.6.1.9
nvidia-cusparse-cu12     12.3.1.170
nvidia-nccl-cu12         2.21.5
nvidia-nvjitlink-cu12    12.4.127
nvidia-nvtx-cu12         12.4.127
omegaconf                2.3.0
opencv-python            4.10.0.84
packaging                24.1
pillow                   11.0.0
pip                      24.2
psutil                   6.1.0
PyYAML                   6.0.2
regex                    2024.9.11
requests                 2.32.3
safetensors              0.4.5
scipy                    1.13.1
setuptools               75.1.0
sympy                    1.13.1
tokenizers               0.20.1
torch                    2.5.0
tqdm                     4.66.5
transformers             4.45.2
triton                   3.1.0
typing_extensions        4.12.2
urllib3                  2.2.3
Werkzeug                 3.0.4
wheel                    0.44.0
zipp                     3.20.2

**Comment by CHDTevior** [comment]
Solved，with this version:欢迎搭乘通往黑洞的直通车。。。。:
diffuser 0.25.0

欢迎搭乘通往黑洞的直通车。。。。:
Successfully installed huggingface_hub-0.23.2

**Comment by limuloo** [comment]
> Solved，with this version:欢迎搭乘通往黑洞的直通车。。。。: diffuser 0.25.0
> 
> 欢迎搭乘通往黑洞的直通车。。。。: Successfully installed huggingface_hub-0.23.2

👌🏻
